title: The Education Gateway to the Proto-OKN
logo: assets/images/edugate-logo.png
description: The Education Gateway to the Proto-OKN
show_downloads: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
